# Generated by Django 4.1.6 on 2023-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_validator', '0002_alter_podcast_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='album',
        ),
        migrations.AddField(
            model_name='podcast',
            name='album_id',
            field=models.IntegerField(null=True),
        ),
    ]
