# Generated by Django 4.1.6 on 2023-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_validator', '0003_remove_podcast_album_podcast_album_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('favourites', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
