# Generated by Django 4.1.6 on 2023-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_validator', '0004_favourites_alter_album_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('podcast_id', models.IntegerField()),
                ('podcast_timestamp', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
