# Generated by Django 3.2.11 on 2023-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_validator', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column_number', models.IntegerField()),
                ('error_message', models.TextField()),
            ],
        ),
    ]
