# Generated by Django 3.2.11 on 2023-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_validator', '0008_validationerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationerror',
            name='column_number',
        ),
        migrations.RemoveField(
            model_name='validationerror',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='validationerror',
            name='row_number',
        ),
        migrations.AddField(
            model_name='validationerror',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='validationerror',
            name='error_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
